name: "RanksPM"
author: "BlckqPlugins"
main: Rang\Main\Rang
version: "1.0.0"
api: [4.0.0]
permissions:
  nick.set:
    default: op
    description: permission
  rank.admin:
    default: op
    description: permission